#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

dev_cert_conf_dir: "{{playbook_dir}}/../cert/"
dev_registry_port: 5000
dev_registry_name: dev-registry
dev_registry_mirror: ""
dev_registry_certs_prefix: "Intel"
dev_registry_certs_path:
  ubuntu: /usr/local/share/ca-certificates
  debian: /usr/local/share/ca-certificates
  centos: /etc/pki/ca-trust/source/anchors
  rhel: /etc/pki/ca-trust/source/anchors
