---
# tasks file for phy_virtualmachine
- name: Create a directory if it does not exist
  file:
    path: "{{ deployDir }}/workload"
    state: directory

- name: copy files from local to remote
  copy:
    src: files/
    dest: "{{ deployDir }}/workload"

- name: exec workload tasks
  shell: cd "{{ deployDir }}/workload";chmod +x *.sh ; sudo ./start.sh
  register: shell_result

- debug:
    msg: "{{shell_result.stdout_lines}}"
