#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
version: "3.7"

services:
  db:
    container_name: postgres
    image: postgres:11-alpine
    networks:
      - main
    ports:
      - "5432:5432"
    restart: "always"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "taas"

  frontend:
    container_name: frontend
    build:
      args:
        - https_proxy
        - http_proxy
      context: ./frontend
    networks:
      - main
    ports:
      - "8079:8079"
    volumes:
      - ./frontend:/frontend/:rw
      - /frontend/node_modules
    depends_on:
      - backend
      - db
    restart: "no"
    read_only: true

  backend:
    container_name: backend
    build:
      args:
        - https_proxy
        - http_proxy
      context: ./backend
    command: sh -c "./start_dev_docker.sh"
    environment:
      DJANGO_SETTINGS_MODULE: taas.settings_dev_docker
      VAULT_ADDR: ""
      VAULT_TOKEN: ""
    read_only: true
    restart: "always"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ./frontend:/frontend:rw
      - ./backend:/backend:rw
      - ../setup/cert/:/backend/cert/:ro
      - static:/backend/static
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
    ports:
      - "8899:8899"
    networks:
      - main
    depends_on:
      - db

volumes:
  static:
  postgresql-data:

networks:
  main:
    driver: bridge
